### PR TITLE
Brian/userapi endpoints

### PR DESCRIPTION
**Pull request by brian6466**
Added the following endpoints for User Api:

User Controller:
POST /user - Creates a user
GET /user - Returns a list of all users
GET /user/{userId} - Returns specific user
PUT /user/{userId} - Updates a existing user
PUT /user/ban/{userId} - Bans a user
PUT /user/unban/{userId} - Unbans a user
DELETE /user/{userId} - Deletes  a user

Follow Controller:
POST /users/{followerId}/follow/{followingId} - Follows a user
DELETE /users/{followerId}/unfollow/{followingId} - Unfollows a user
GET /users/{userId}/followers - Gets users followers
GET /users/{userId}/following - Gets users following

### CODE REVIEW

**Review by CraigPhayer — APPROVED** [review]
All good, think the pipeline needs to be changed to java 17 or 11 looking at the error its throwing

**Comment by CraigPhayer** [comment]
[Implement follow actions for UserAPI](https://trello.com/c/XRgcvYeC/26-implement-follow-actions-for-userapi)

**Comment by CraigPhayer** [comment]
[Implement basic endpoints for UserAPI](https://trello.com/c/mRYDxM3v/27-implement-basic-endpoints-for-userapi)

**Comment by brian6466** [comment]
> All good, think the pipeline needs to be changed to java 17 or 11 looking at the error its throwing

Updated the lombok to a newer version, which fixed the issue

**Review by jamespb20 — APPROVED** [review]
looks good

**Pull request merged**
